rootProject.name = "VexCore"

include(
    "vexcore-api",
    "vexcore-service-registry",
    "vexcore-configuration",
    "vexcore-command",
    "vexcore-cache",
    "vexcore-signal",
    "vexcore-data",
    "vexcore-localization",
    "vexcore-messaging",
    "vexcore-gameplay-api",
    "vexcore-gameplay",
    "vexcore-inventory",
    "vexcore-dialog",
    "vexcore-items:common",
    "vexcore-items:versions:v26_2",
    "vexcore-packets:common",
    "vexcore-packets:versions:v26_2",
    "vexcore-paper-api",
    "vexcore-paper",
    "vexcore-velocity-api",
    "vexcore-velocity",
)
