package dev.vexsoft.core.packets.version;

public enum PacketCapability {
  BUNDLE_PACKETS,
  DISPLAY_ENTITIES,
  DISPLAY_PASSENGERS,
  ENTITY_GLOW,
  ENTITY_HIT_ANIMATION,
  LIGHTNING,
  INTERACTABLE_HOLOGRAMS,
  FAKE_ITEM_META
}
